-- AlterTable
ALTER TABLE `caseupdate` ADD COLUMN `assignedTo` INTEGER NOT NULL DEFAULT 1,
    ADD COLUMN `dueDate` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    ADD COLUMN `priority` ENUM('LOW', 'MEDIUM', 'HIGH') NOT NULL DEFAULT 'LOW',
    ADD COLUMN `status` ENUM('PENDING', 'INPROGRESS', 'FINISHED') NOT NULL DEFAULT 'PENDING';

-- AddForeignKey
ALTER TABLE `CaseUpdate` ADD CONSTRAINT `CaseUpdate_assignedTo_fkey` FOREIGN KEY (`assignedTo`) REFERENCES `Lawyer`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;
